# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{test_notifier}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nando Vieira"]
  s.date = %q{2010-03-11}
  s.description = %q{Display system notifications (dbus, growl and snarl) after
running tests. It works on Mac OS X, Linux and Windows. Powerful when used
with Autotest ZenTest gem for Rails apps.
}
  s.email = %q{fnando.vieira@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "lib/test_notifier.rb",
     "lib/test_notifier/autotest.rb",
     "lib/test_notifier/icons/error.png",
     "lib/test_notifier/icons/failure.png",
     "lib/test_notifier/icons/passed.png",
     "lib/test_notifier/register-growl.scpt",
     "lib/test_notifier/rspec.rb",
     "lib/test_notifier/test_unit.rb"
  ]
  s.homepage = %q{http://github.com/fnando/test_notifier}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.requirements = ["You'll need Growl (Mac OS X), Libnotify (Linux) or Snarl (Windows)"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Display system notifications (dbus, growl and snarl) after running tests.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

